import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import eslintConfigPrettier from "eslint-config-prettier";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  eslintConfigPrettier,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `wrangler types` (npm run cf-typegen) — not source.
    "cloudflare-env.d.ts",
    // OpenNext's Cloudflare build output (npm run preview/deploy) — not source.
    ".open-next/**",
  ]),
]);

export default eslintConfig;
