/**
 * Custom Worker entry (wrangler.jsonc "main"), per OpenNext's Cloudflare
 * "custom worker" pattern. It answers GET/HEAD /media/<id> itself (see
 * src/lib/serveMedia.ts for why that can't live in a Next.js route) and
 * hands every other request to the OpenNext-generated handler unchanged.
 */
import type { ExecutionContext } from "@cloudflare/workers-types";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- exists only after a build
// @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
import { default as handler } from "../.open-next/worker.js";
import { serveMedia } from "./lib/serveMedia";

const MEDIA_PATH = /^\/media\/([^/]+)$/;

const worker = {
  async fetch(request: Request, env: CloudflareEnv, ctx: ExecutionContext) {
    if (request.method === "GET" || request.method === "HEAD") {
      const match = MEDIA_PATH.exec(new URL(request.url).pathname);
      if (match) return serveMedia(request, decodeURIComponent(match[1]), env);
    }
    return handler.fetch(request, env, ctx);
  },
};

export default worker;

// Durable Object classes the generated worker exports — re-exported
// unchanged so the Worker keeps the same shape as OpenNext's default entry.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- exists only after a build
// @ts-ignore generated at build time (see above).
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "../.open-next/worker.js";
